GET http://localhost:8099/spring-mvc-app/api/v1/product/all
Authorization: Basic 123 123

###

GET http://localhost:8099/spring-mvc-app/api/v1/product/1
Authorization: Basic 123 123
###

POST http://localhost:8099/spring-mvc-app/api/v1/product
#Authorization: Basic guest guest
Authorization: Basic 123 123
Content-Type: application/json

  {
    "productname": "Milk",
    "title": "Soy milk",
    "price": 300.00
  }

###

PUT http://localhost:8099/spring-mvc-app/api/v1/product
Authorization: Basic 123 123
Content-Type: application/json

{
  "id": 16,
  "productname": "Milk",
  "title": "Soy milk",
  "price": 400.00
}

###

DELETE http://localhost:8099/spring-mvc-app/api/v1/product/16
Authorization: Basic 123 123
###

POST http://localhost:8099/spring-mvc-app/api/v1/cart/1/user/2/product?qty=1
#Authorization: Basic guest guest
Authorization: Basic 123 123
###

GET http://localhost:8099/spring-mvc-app/api/v1/cart/1/user
#Authorization: Basic guest guest
Authorization: Basic 123 123